# Generated by Django 2.0 on 2022-11-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('voter_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('a_community', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('born_year', models.PositiveIntegerField(null=True)),
                ('civil_state', models.CharField(max_length=10, null=True)),
                ('sexuality', models.CharField(max_length=20, null=True)),
                ('works', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'name', 'surname', 'city', 'a_community', 'gender', 'born_year', 'civil_state', 'sexuality', 'works')},
        ),
    ]
