# Generated by Django 2.0 on 2022-12-10 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20221124_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='voting_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None),
        ),
    ]
