# Generated by Django 2.0 on 2022-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20221210_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='voting_id',
            field=models.PositiveIntegerField(),
        ),
    ]
