# Generated by Django 2.0 on 2022-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221115_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT'), ('DROOP', 'DROOP')], default='IDENTITY', max_length=255),
        ),
    ]
