# Generated by Django 2.0 on 2022-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221115_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tipo',
            field=models.CharField(choices=[('O', 'Options'), ('S', 'Score')], default='O', max_length=1),
        ),
    ]
