# Generated by Django 2.0 on 2022-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221115_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT'), ('DROOP', 'DROOP'), ('BORDA', 'BORDA')], default='IDENTITY', max_length=255),
        ),
    ]
