# Generated by Django 2.0 on 2022-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20221117_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('CV', 'CLASSIC VOTING'), ('PV', 'PREFERENCE VOTING'), ('BV', 'BINARY VOTING'), ('SV', 'SCORE VOTING')], default='CV', max_length=2),
        ),
    ]
