# Generated by Django 2.0 on 2022-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20221117_2136'),
        ('voting', '0006_auto_20221121_1816'),
    ]

    operations = [
    ]
