# Generated by Django 2.0 on 2022-11-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20221123_0932'),
        ('voting', '0007_voting_voting_type'),
    ]

    operations = [
    ]
