# Generated by Django 2.0 on 2022-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voting_voting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_ordination',
            field=models.BooleanField(default=False, verbose_name='Create ordination'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tipo',
            field=models.CharField(choices=[('O', 'Options'), ('S', 'Score'), ('P', 'Preference')], default='O', max_length=1),
        ),
    ]
