# Generated by Django 2.0 on 2022-11-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20221123_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT'), ('DROOP', 'DROOP'), ('BORDA', 'BORDA'), ('HARE', 'HARE')], default='IDENTITY', max_length=255),
        ),
    ]
