# Generated by Django 2.0 on 2022-11-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20221126_1259'),
        ('voting', '0008_auto_20221125_0618'),
    ]

    operations = [
    ]
