# Generated by Django 2.0 on 2022-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_merge_20221127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
