# Generated by Django 2.0 on 2022-12-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20221128_1548'),
        ('voting', '0008_auto_20221125_1737'),
    ]

    operations = [
    ]
