# Generated by Django 2.0 on 2022-12-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_merge_20221204_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tipo',
            field=models.CharField(choices=[('O', 'Options'), ('S', 'Score'), ('R', 'Ranked question'), ('B', 'Yes/No question')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('CV', 'CLASSIC VOTING'), ('RV', 'RANKED VOTING'), ('BV', 'BINARY VOTING'), ('SV', 'SCORE VOTING')], default='CV', max_length=2),
        ),
    ]
