# Generated by Django 2.0 on 2022-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_merge_20221204_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT'), ('DROOP', 'DROOP'), ('HARE', 'HARE')], default='IDENTITY', max_length=255),
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
