# Generated by Django 2.0 on 2022-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20221207_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tipo',
            field=models.CharField(choices=[('C', 'Classic question'), ('S', 'Score question'), ('R', 'Ranked question'), ('B', 'Yes/No question')], default='C', max_length=1),
        ),
    ]
