# Generated by Django 2.0 on 2022-12-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_merge_20221125_0711'),
        ('voting', '0014_auto_20221208_1659'),
    ]

    operations = [
    ]
