# Generated by Django 2.0 on 2022-12-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20221124_1714'),
        ('voting', '0014_auto_20221208_1659'),
    ]

    operations = [
    ]
