# Generated by Django 2.0 on 2022-12-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_merge_20221209_1707'),
        ('voting', '0015_merge_20221209_1535'),
    ]

    operations = [
    ]
