# Generated by Django 2.0 on 2022-12-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20221209_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tipo',
            new_name='type',
        ),
    ]
