# Generated by Django 2.0 on 2022-12-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20221209_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='voting_type',
        ),
    ]
