# Generated by Django 2.0 on 2022-12-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_merge_20221210_1518'),
        ('voting', '0017_remove_voting_voting_type'),
    ]

    operations = [
    ]
