# Generated by Django 2.0 on 2022-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_merge_20221210_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT'), ('DROOP', 'DROOP'), ('IMPERIALI', 'IMPERIALI'), ('BORDA', 'BORDA'), ('HARE', 'HARE'), ('REINFORCED_IMPERIAL', 'REINFORCED_IMPERIAL'), ('HAGENBACH_BISCHOFF', 'HAGENBACH_BISCHOFF'), ('SAINTE_LAGUE', 'SAINTE_LAGUE'), ('MODIFIED_SAINTE_LAGUE', 'MODIFIED_SAINTE_LAGUE')], default='IDENTITY', max_length=255),
        ),
    ]
