# Generated by Django 2.0 on 2022-12-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20221211_1240'),
        ('voting', '0013_auto_20221206_1554'),
    ]

    operations = [
    ]
