# Generated by Django 2.0 on 2022-12-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20221211_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Classic question'), ('S', 'Score question'), ('R', 'Ranked question'), ('B', 'Yes/No question'), ('I', 'Image')], default='C', max_length=1),
        ),
    ]
