# Generated by Django 2.0 on 2022-12-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_merge_20221214_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Classic question'), ('S', 'Score question'), ('R', 'Ranked question'), ('B', 'Yes/No question'), ('I', 'Image')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT'), ('DROOP', 'DROOP'), ('IMPERIALI', 'IMPERIALI'), ('BORDA', 'BORDA'), ('HARE', 'HARE'), ('REINFORCED_IMPERIAL', 'REINFORCED_IMPERIAL'), ('HAGENBACH_BISCHOFF', 'HAGENBACH_BISCHOFF'), ('SAINTE_LAGUE', 'SAINTE_LAGUE'), ('MODIFIED_SAINTE_LAGUE', 'MODIFIED_SAINTE_LAGUE')], default='IDENTITY', max_length=255),
        ),
    ]
