# Generated by Django 2.0 on 2022-12-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_auto_20221216_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingFromFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_voting', models.FileField(upload_to='')),
                ('voting', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.Voting')),
            ],
        ),
    ]
