# Generated by Django 2.0 on 2022-12-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_votingfromfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='future_start',
            new_name='scheduled_start',
        ),
    ]
