# Generated by Selenium IDE
import pytest
import time
import json
from .models import Census
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFilterCensus():
  def setUp(self):
        #Load base test functionality for decide
        self.base = BaseTestCase()
        self.base.setUp()

        options = webdriver.ChromeOptions()
        options.headless = True
        self.driver = webdriver.Chrome(options=options)

        super().setUp()            

  def tearDown(self):           
      super().tearDown()
      self.driver.quit()

      self.base.tearDown()
  
  def test_filterCensus(self):
    self.driver.get("http://127.0.0.1:8000/census/")
    self.driver.set_window_size(930, 704)
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(7) .card-title").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Roger")
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(4) .input-group-text").click()
    self.driver.find_element(By.NAME, "i").click()
    self.driver.find_element(By.NAME, "i").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(2) .input-group-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(7) .input-group-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".a2 > .card-body > .card-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".a2 > .card-body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(4) .card-title").click()
    self.driver.find_element(By.NAME, "myfile").click()
    self.driver.find_element(By.NAME, "myfile").send_keys("C:\\fakepath\\Datos1.xlsx")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(7) .card-title").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Roger")
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(4) .input-group-text").click()
    self.driver.find_element(By.NAME, "i").click()
    self.driver.find_element(By.NAME, "i").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(2) .input-group-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(12) .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(12) .form-control").send_keys("0")
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(12) .input-group-text").click()